### ISSUE TITLE
CSV module doesn't add quotes around commas

### ISSUE THREAD

**Issue by ghislainfourny** [28msec/cellstore#1006]
http://secxbrl.28.io/v1/_queries/public/api/facttable-for-component.jq?token=foobar&ticker=ko&fiscalYear=ALL&fiscalPeriod=FY&merge=false&disclosure=BalanceSheet&format=html

**Comment by fcavalieri** [comment]
Fixed by https://github.com/28msec/zorba/pull/167

**Comment by ghislainfourny** [comment]
Hi Federico,

Is it already merged into the platform, and does the secxbrl project need an update to the newer platform version?

Thanks and kind regards,
Ghislain
