### ISSUE TITLE
empty sequence error with labels=true

### ISSUE THREAD

**Issue by dknochen** [28msec/cellstore#524]
{{secxbrl}}/v1/_queries/public/api/facts.jq?_method=POST&xbrl%3AConcept=us-gaap%3AOwnshareLendingArrangementSharesIssued&token={{token}}&sec:FiscalYear=2012&labels=true

{
    "request_id": "547dfd7bb5c00423018a9f7f",
    "context": "secxbrl.28.io",
    "type": "type",
    "code": "XPTY0004",
    "location": {
        "module": "/public/api/facts.jq",
        "line-number": 219,
        "line-number-end": 219,
        "column-number": 79,
        "column-number-end": 90
    },
    "description": "empty-sequence() can not be treated as type xs:string",
    "message": "</public/api/facts.jq>:219,79: type error [err:XPTY0004]: empty-sequence() can not be treated as type xs:string"
}

**Comment by gislenius** [comment]
That's solved.
