### ISSUE TITLE
28:watch doesn't work on windows

### ISSUE THREAD

**Issue by dknochen** [28msec/cellstore#579]
Can it be that its because of the backslash in the windows file paths?

![image](https://cloud.githubusercontent.com/assets/1012324/5631014/54b668e8-95c3-11e4-9e5e-74c268bad547.png)

**Comment by wcandillon** [comment]
If it's because of the \, why would the setup work then? Can you try to add some debug logs in the tasks/28.js in order to get more information about this issue?
