### ISSUE TITLE
Wrong edinet code selects all entities.

### ISSUE THREAD

**Issue by wcandillon** [28msec/cellstore#752]
Example url: http://edinet.28.io/v1/_queries/public/api/facts.jq?token=255f69dc-8c80-4d2c-8dc0-7811b7f0d13b&format=xml&&edinetcode=E02274-000&fiscalYear=ALL&concept=jpcrp-cor%3ATotalAssetsIFRSSummaryOfBusinessResults&concept=jpcrp-cor%3AProfitLossAttributableToOwnersOfParentIFRSSummaryOfBusinessResults&fiscalPeriod=FY

**Comment by gislenius** [comment]
That's solved (error is thrown instead).
