### ISSUE TITLE
Broken link in cell store manager

### ISSUE THREAD

**Issue by gislenius** [28msec/cellstore#838]
When you navigate to a concept or to synonyms/formulas, the go-home link (top-left corner of screen) is broken (Page not found).

**Comment by gislenius** [comment]
Also, the link to the account (top-right is broken). We mentioned migrating the account page to the cell store at some point I think.

**Comment by dknochen** [comment]
![image](https://cloud.githubusercontent.com/assets/1012324/6807771/e1447c2c-d250-11e4-8c73-22360dc3ac4f.png)
