### ISSUE TITLE
duplicate entries in create new report

### ISSUE THREAD

**Issue by dknochen** [28msec/cellstore#917]
When creating a new report in the cellstore manager, there are duplicate reports. We should either add a description explaining the difference, or remove one of them:

![image](https://cloud.githubusercontent.com/assets/1012324/7023152/247d18d6-dd33-11e4-8dc6-e9129ed2aa40.png)

**Comment by gislenius** [comment]
@dknochen there's no difference. It's just duplicates because of the way Charlie organizes report frames. It might get fixed in the future if he manages to provide a single package.

**Comment by gislenius** [comment]
Adding a documentation string with the style of reporting would make it clearer I think. So it's a bug.
