### ISSUE TITLE
additional column in facttable-for-component

### ISSUE THREAD

**Issue by dknochen** [28msec/cellstore#959]
http://secxbrl.28.io/v1/_queries/public/api/facttable-for-component.jq?token=c3049752-4d35-43da-82a2-f89f1b06f7a4&format=html&disclosure=BalanceSheet&profile-name=sec&labels=true&ticker=vz

![image](https://cloud.githubusercontent.com/assets/1012324/7257277/b36f31ba-e854-11e4-97f8-467a1cf6a456.png)

**Comment by gislenius** [comment]
Oops, there's a *zorba* bug in the csv module -- it doesn't protect commas with quotes...

**Comment by ghislainfourny** [comment]
This will be fixed as soon as the next 28.io is released.
